### ISSUE TITLE
migration to 1.3.7 failed

### ISSUE THREAD

**Issue by patricegautier** [Nico640/docker-unms#50] opened 2021-02-01 23:41 UTC
Well the good news  was that 1.3.7 is here, here is the bad news :( :

tail ~/unms/config/unms/logs/unms.log

`Running docker-entrypoint /home/app/unms/index.js
Sentry release: 
Version: 1.3.7+08951661e0.2021-01-24T13:54:56+01:00
Waiting for database containers
NOTICE:  extension "timescaledb" does not exist, skipping
DROP EXTENSION
Restoring backups and/or running migrations
yarn run v1.22.4
$ yarn backup:apply && yarn migrate && yarn check-crm-db
$ node ./cli/apply-backup.js
$ node ./cli/migrate.js
{"name":"UNMS","hostname":"83b53e3ba0c3","pid":17234,"level":30,"msg":"Connected to SiriDB server version: 2.0.42","time":"2021-02-01T23:37:11.568Z","v":0}
{"name":"UNMS","hostname":"83b53e3ba0c3","pid":17234,"level":30,"msg":"SiriDB database 'unms' does not exists. Creating...","time":"2021-02-01T23:37:11.573Z","v":0}
Migration failed: SiriDbError: database directory already exists: /config/siridb/unms/
    at SiriDbConnection.resolveRequest (/home/app/unms/lib/siridb/connection.js:206:17)
    at SiriDbConnection.handleData (/home/app/unms/lib/siridb/connection.js:148:14)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  tp: 96
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Running docker-entrypoint /home/app/unms/index.js
Sentry release: 
Version: 1.3.7+08951661e0.2021-01-24T13:54:56+01:00
Waiting for database containers
NOTICE:  extension "timescaledb" does not exist, skipping
DROP EXTENSION
Restoring backups and/or running migrations
yarn run v1.22.4
$ yarn backup:apply && yarn migrate && yarn check-crm-db
$ node ./cli/apply-backup.js
{"name":"netflow","hostname":"83b53e3ba0c3","pid":760,"level":40,"msg":"DB schema version mismatch. DB schema version: 1.2.7, UNMS version: 1.3.7","time":"2021-02-01T23:37:15.668Z","v":0}
$ node ./cli/migrate.js
{"name":"UNMS","hostname":"83b53e3ba0c3","pid":17378,"level":30,"msg":"Connected to SiriDB server version: 2.0.42","time":"2021-02-01T23:37:17.845Z","v":0}
{"name":"UNMS","hostname":"83b53e3ba0c3","pid":17378,"level":30,"msg":"SiriDB database 'unms' does not exists. Creating...","time":"2021-02-01T23:37:17.851Z","v":0}
Migration failed: SiriDbError: database directory already exists: /config/siridb/unms/
    at SiriDbConnection.resolveRequest (/home/app/unms/lib/siridb/connection.js:206:17)
    at SiriDbConnection.handleData (/home/app/unms/lib/siridb/connection.js:148:14)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  tp: 96
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Running docker-entrypoint /home/app/unms/index.js
Sentry release: 
Version: 1.3.7+08951661e0.2021-01-24T13:54:56+01:00
Waiting for database containers
NOTICE:  extension "timescaledb" does not exist, skipping
DROP EXTENSION
Restoring backups and/or running migrations
yarn run v1.22.4
$ yarn backup:apply && yarn migrate && yarn check-crm-db
$ node ./cli/apply-backup.js
$ node ./cli/migrate.js
`

.. and so on.

**Comment by patricegautier** [comment] 2021-02-02 01:14
>  Migration failed: SiriDbError: database directory already exists: /config/siridb/unms/ at SiriDbConnection.resolveRequest (/home/app/unms/lib/siridb/connection.js:206:17) 

It indeed did, and moving it aside resulted in the controller launching and general happiness.  Not  sure what was lost in the process..

**Comment by ds2288** [comment] 2021-02-07 23:54
Happened to me too. Had to delete entire container and files and start from scratch. Not a huge issue for me though, my config is basic.

**Comment by headwhacker** [comment] 2021-03-06 09:41
When I update my UNMS container to this version, all my nodes show as unreachable from from the devices list except for other ubiquiti devices (ER4, ES8-150W, ES24-lite & ES10X). Rolling back to 1.2.7 is the only option to fix the issue. Has anyone experience the same scenario?

**Comment by Nico640** [comment] 2022-01-31 21:48
This was caused by some sort of SiriDB database corruption and was fixed by the second 1.3.7 image. Please open a new issue if there are still issues with this.

**Closed by Nico640** 2022-01-31 21:48 UTC
