### ISSUE TITLE
System Backup over the UNMS Webinterface Failed

### ISSUE THREAD

**Issue by pr3mi3r3** [Nico640/docker-unms#2] opened 2019-08-09 09:07 UTC
Hello,
I can not do any Backups over the UNMS Webinterface.
I get an error every time.
Can you help me?

Best regards
pr3mi3r3

**Comment by Nico640** [comment] 2019-08-09 18:23
This seems to be caused by UNMS trying to backup UCRM.
However, UCRM isn't installed in the image yet.

Logs:
`{"name":"UNMS","hostname":"c6e0f2be15f0","pid":1461,"level":50,"err":{"message":"UCRM backup timed out.","name":"Error","stack":"Error: UCRM backup timed out.\n    at Timeout.setTimeout (/home/app/unms/lib/crm/service.js:140:14)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at unrefdHandle (timers.js:520:7)\n    at Timer.processTimers (timers.js:222:12)"},"msg":"Failed to create backup","time":"2019-08-09T18:12:29.322Z","v":0} `

I don't think this can be fixed without installing UCRM, which I am still working on.

**Comment by pr3mi3r3** [comment] 2019-08-14 07:04
ok thanks for the feedback, I will do a manual backup via Bash.
Hopefully you will implement UCRM soon... Good luck

**Comment by Nico640** [comment] 2019-08-28 13:18
I would probably just backup the whole /config folder

**Comment by Nico640** [comment] 2019-09-22 19:42
UCRM is now integrated and this issue is fixed in the latest build.

**Closed by Nico640** 2019-09-22 19:42 UTC
Labels: bug

**Comment by patricegautier** [comment] 2019-09-23 02:18
Confirm that - thanks Nico!
