### ISSUE TITLE
armhf build not working on pi4?

### ISSUE THREAD

**Issue by NEITG** [Nico640/docker-unms#10] opened 2019-09-29 10:35 UTC
Hi, I just had to redeploy your UNMS package into Docker on Pi4. Had it working okay a few weeks back but trying to run my same Docker deployment script using the armhf tag I'm now getting an unsupported platform error. 

Any known issues for this in the current build?

Thanks

**Comment by Nico640** [comment] 2019-09-29 19:46
Hi,
I have no problems running the image on a Pi4 with the armhf tag.
I am using the command specified in the readme (docker run), what are you using to deploy the image?
The only thing that changed architecture wise is that with the move from Travis CI to GitLab CI, the armhf image shows up as amd64 on the docker hub, even though it is build for and from arm. I haven't looked into that yet as I didn't have any problems.

**Comment by NEITG** [comment] 2019-10-01 17:34
Sure, it's below. This is the same command that worked a month or so back.

Many thanks


docker service create \
  --name=unms \
  --publish=8080:80/tcp \
  --publish=8443:443/tcp \
  --publish 2055:2055/udp \
  --env TZ=Europe/London \
  --constraint=node.id==manager \
  --mount=type=bind,src=/home/pi/unms,dst=/config \
  nico640/docker-unms:armhf

**Comment by NEITG** [comment] 2019-10-01 18:35
Thats a typo on the constraint where I was trying to get it working but with or without it fails

**Comment by Nico640** [comment] 2019-10-01 20:04
Hi,
The problem is indeed the architecture that is displayed incorrectly on the docker hub.
I'm gonna look into getting that fixed. In the meantime, you can use the --no-resolve-image parameter on the docker service create command to stop docker from checking whether the architecture is correct.

**Comment by NEITG** [comment] 2019-10-01 20:12
Great, thanks I shall give that a try

**Comment by zimmertr** [comment] 2019-10-02 03:19
The following `docker-compose.yml` file fails on my Odroid XU4Q. Which is an `ARMv7` device. Any idea why?

```
version: '3'
services:
    unms:
        image: nico640/docker-unms:armhf
        restart: unless-stopped
        container_name: unms
        ports:
            - 81:80
            - 444:443
            - 2055:2055/udp
        volumes:
            - /root/docker/unms/:/config
        environment:
            - TZ=America/Los_Angeles
            - PUBLIC_HTTPS_PORT=444
            - PUBLIC_WS_PORT=443
```

Here is the error message on startup: 
```
$> docker-compose up -d
Creating unms ... error

ERROR: for unms  Cannot start service unms: no status provided on response: unknown

ERROR: for unms  Cannot start service unms: no status provided on response: unknown
ERROR: Encountered errors while bringing up the project.
```

**Comment by Nico640** [comment] 2019-10-02 18:54
Hi,
No idea, your docker-compose.yml works fine on a Pi4.
Does the image run without docker compose?

**Comment by NEITG** [comment] 2019-10-02 19:02
The --no-resolve-image parameter has got the service running. My UNMS is stuck on "UNMS is Starting..." but that's more likely down to the remains of my previous service.

**Comment by zimmertr** [comment] 2019-10-02 19:39
@Nico640 , not it doesn't unfortunately. The same error is produced.

**Comment by NEITG** [comment] 2019-10-05 09:52
Just to say, once I trashed my UNMS folder and started again I'm all back up and working. So this can be closed for my particular issue.
Just to check, what is the correct process for updating so that I don't trash it again?
Thanks for the help

**Comment by Nico640** [comment] 2019-10-05 18:55
Hi,
there isn't really a specific process for updating.
Everything important is kept in the /config volume, so you could delete the docker and recreate it, or in your case, you could use the "docker service update --image" command.
Not sure what happened to your UNMS install, it shouldn't get stuck after an update.
Be sure to share your logs if it happens again.

**Comment by zimmertr** [comment] 2019-10-06 23:22
@Nico640 turns out my issue was an artifact of updating docker (or a related package) on Arch Linux ARM. Rebooting the OS fixed it.

**Comment by Nico640** [comment] 2019-10-07 15:31
@zimmertr I'm glad you found the issue!

**Comment by Nico640** [comment] 2019-10-08 19:39
The "unsupported platform" issue should be fixed in the latest build. The image architecture now shows up correctly on docker hub.

**Closed by Nico640** 2019-10-08 19:39 UTC
